-- insert countries
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('1', 'Albania');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('2', 'Andorra');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('3', 'Austria');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('4', 'Belarus');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('5', 'Belgium');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('6', 'Bosnia');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('7', 'Bulgaria');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('8', 'Croatia');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('9', 'Cyprus');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('10', 'Czech Republic');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('11', 'Denmark');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('12', 'Estonia');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('13', 'Finland');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('14', 'France');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('15', 'Germany');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('16', 'Gibraltar');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('17', 'Greece');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('18', 'Greenland');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('19', 'Guernsey');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('20', 'Hungary');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('21', 'Iceland');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('22', 'Faroe Islands');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('23', 'Ireland');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('24', 'Italy');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('25', 'Jersey');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('26', 'Latvia');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('27', 'Liechtenstein');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('28', 'Lithuania');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('29', 'Luxemburg');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('30', 'Macedonia');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('31', 'Malta');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('32', 'Island of Man');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('33', 'Moldova');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('34', 'Monaco');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('35', 'Netherlands');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('36', 'Norway');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('37', 'Poland');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('38', 'Portugal');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('39', 'Romania');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('40', 'Russia');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('41', 'San Marino');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('42', 'Serbia');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('43', 'Montenegro');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('44', 'Slovakia');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('45', 'Slovenia');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('46', 'Spain');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('47', 'Sylbarn and Jan Mayen Islands');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('48', 'Sweeden');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('49', 'Switzerland');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('50', 'Turkey');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('51', 'Ukraine');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('52', 'United Kingdom');
INSERT INTO `enercom`.`countries` (`id`, `name`) VALUES ('53', 'Vatican City');

--insert network operators
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('1', 'Albtelecom', '1');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('2', 'Albanian Fibre Backbone', '1');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('3', 'Telekom Austria', '3');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('4', 'Tele2', '3');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('5', 'tele.ring', '3');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('6', 'Magenta Telekom', '3');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('7', 'eTel Austria', '3');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('8', 'Beltelecom', '4');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('9', 'Alternative Digital Network', '4');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('10', 'Proximus', '5');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('11', 'COLT Telecom', '5');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('12', 'Orange Belgium', '5');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('13', 'Scarlet', '5');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('14', 'Tele2 Belgium', '5');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('15', 'Telenet', '5');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('16', 'BH Telecom', '6');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('17', 'HT Mostar', '6');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('18', 'Telekom Srpske', '6');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('19', 'Bulgarian Telecommunications Company', '7');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('20', 'A1 Bulgaria', '7');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('21', 'Hrvatski Telekom', '8');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('22', 'A1 Croatia', '8');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('23', 'Optima Telekom', '8');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('24', 'Metronet', '8');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('25', 'Cytamobile-Vodafone', '9');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('26', 'Epic', '9');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('27', 'PrimeTel', '9');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('28', 'O2 Czech Republic', '10');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('29', 'CETIN', '10');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('30', 'Ceske Radiokomunikace', '10');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('31', 'GTS Czech', '10');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('32', 'CD-Telematika', '10');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('33', 'VOLNY', '10');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('34', 'TDC', '11');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('35', 'Telenor Denmark', '11');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('36', 'Telia Denmark', '11');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('37', 'Telia Estonia', '12');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('38', 'Tele2 Estonia', '12');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('39', 'Elisa', '12');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('40', 'Telekom Albania', '1');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('41', 'Vodafone Albania ', '1');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('42', 'Plus Communications', '1');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('43', '3 Austria ', '3');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('44', 'Orange Austria ', '3');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('45', 'Belcel/Diallog', '4');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('46', 'A1 Belarus', '4');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('47', 'Mobile TeleSystems', '4');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('48', 'BeST/life', '4');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('49', 'Telenor Bulgaria', '7');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('50', 'Tele2 Croatia', '8');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('51', 'MTN Cyprus', '9');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('52', 'Kibris Telekom', '9');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('53', 'O2 Czech Republic', '10');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('54', 'T-Mobile Czech Republic', '10');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('55', 'Vodafone Czech Republic', '10');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('56', 'Nordic Telecom', '10');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('57', '3 Denmark', '11');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('58', 'Telia Finland', '13');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('59', 'Finnet Group', '13');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('60', 'DNA', '13');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('61', 'Elisa', '13');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('62', 'TDC Finland', '13');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('63', 'Tele2', '13');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('64', 'Orange', '14');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('65', 'Altice France', '14');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('66', 'Free Iliad', '14');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('67', 'Bouygues Telecom', '14');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('68', 'Telekom Deutschland', '15');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('69', 'Vodafone Germany', '15');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('70', 'Freenet', '15');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('71', 'Tele2 Germany', '15');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('72', 'Telefonica Germany', '15');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('73', 'OTE', '17');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('74', 'Wind Hellas', '17');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('75', 'Nova', '17');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('76', 'Vodafone Greece', '17');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('77', 'Cyta Hellas', '17');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('78', 'Cosmote', '17');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('79', 'Maygar Telekom', '20');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('80', 'Digi Telecom/Invitel', '20');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('81', 'Monor', '20');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('82', 'B2B Europe', '20');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('83', 'Antenna Hungaria', '20');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('84', 'T-Mobile Hungary', '20');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('85', 'Telenor', '20');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('86', 'MVPI Mobil', '20');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('87', 'Siminn', '21');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('88', 'Syn', '21');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('89', 'eir', '23');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('90', 'BT Ireland', '23');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('91', 'Smart Telecom', '23');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('92', 'Vodafone Ireland', '23');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('93', '3 Ireland', '23');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('94', 'Telecom Italia', '24');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('95', 'Wind Tre', '24');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('96', 'BT Italia', '24');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('97', 'Tiscali', '24');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('98', 'Fastweb', '24');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('99', 'Vodafone Italy', '24');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('100', 'Iliad', '24');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('101', 'Telecom Kosovo', '54');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('102', 'IPKO', '54');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('103', 'Kujtesa', '54');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('104', 'Vala', '54');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('105', 'Tet', '26');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('106', 'Norby Telecom', '26');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('107', 'Latvia Mobilais Telefons', '26');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('108', 'Tele2 Latvia', '26');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('109', 'Telekom Baltija', '26');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('110', 'Bite Latvia', '26');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('111', 'Telia Leituvos', '28');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('112', 'Bite', '28');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('113', 'Tele2 Lithuania', '28');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('114', 'POST Luxembourg', '29');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('115', 'Cegecom', '29');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('116', 'Proximus Luxembourg', '29');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('117', 'Telecom Luxembourg', '29');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('118', 'Tango', '29');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('119', 'Orange Luxembourg', '29');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('120', 'GO Mobile', '31');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('121', 'Melita', '31');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('122', 'Vodafone Malta', '31');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('123', 'Moldtelecom', '33');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('124', 'InterDnestrCom', '33');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('125', 'Orange Moldova', '33');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('126', 'Eventis', '33');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('127', 'Crnogorski Telekom', '43');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('128', 'Telenor Montenegro', '43');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('129', 'T-Mobile Montenegro', '43');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('130', 'Royal Koninklijke PTT Nederland', '35');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('131', 'Scarlet Telecom', '35');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('132', 'Tele2 Netherlands', '35');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('133', 'Vodafone Ziggo', '35');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('134', 'T-Mobile Netherlands', '35');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('135', 'Makedonski Telekom', '30');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('136', 'A1 Macedonia', '30');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('137', 'Telenor', '36');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('138', 'Telia Norway', '36');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('139', 'NextGenTel', '36');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('140', 'Tele2', '36');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('141', 'BaneTele', '36');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('142', 'Teletopia', '36');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('143', 'Mobile Norway', '36');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('144', 'Ice', '36');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('145', 'Orange Poland', '37');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('146', 'Netia', '37');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('147', 'Telefonia Dialog', '37');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('148', 'Telekomunikacja Kolejowa', '37');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('149', 'T-Mobile Poland', '37');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('150', 'Exatel', '37');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('151', 'P4/Play', '37');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('152', 'Polkomtel/Plus GSM', '37');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('153', 'Altice Portugal', '38');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('154', 'Oni Communications', '38');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('155', 'Sonaecom', '38');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('156', 'Novis', '38');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('157', 'AR Telecom', '38');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('158', 'Jazztel', '38');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('159', 'NOS', '38');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('160', 'Vodafone', '38');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('161', 'MEO', '38');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('162', 'Telekom Romania', '39');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('163', 'Vodafone Romania', '39');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('164', 'Digi Mobil', '39');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('165', 'Svyazinvest', '40');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('166', 'Rostelecom', '40');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('167', 'Central Telegraph', '40');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('168', 'VEON', '40');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('169', 'Multiregional Transit Telecom', '40');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('170', 'TransTeleCom (TTK)', '40');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('171', 'PeterStar', '40');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('172', 'ER-Telecom', '40');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('173', 'MegaFon', '40');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('174', 'Uralsvyazinform', '40');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('175', 'VolgaTelecom', '40');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('176', 'Skylink', '40');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('177', 'Slovak Telekom', '44');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('178', 'Benestra', '44');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('179', 'Slovak Wireless Access Network', '44');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('180', 'T-Mobile Slovakia', '44');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('181', 'Orange Slovakia', '44');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('182', 'O2 Slovakia', '44');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('183', 'Telekom Slovenije', '45');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('184', 'A1 Slovenia (Amis Telekom)', '45');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('185', 'T-2', '45');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('186', 'Telemach Mobil', '45');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('187', 'Telefónica', '46');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('188', 'Orange Spain', '46');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('189', 'Vodafone Spain', '46');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('190', 'Másmóvil', '46');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('191', 'Movistar', '46');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('192', 'Telia Company', '48');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('193', 'Tele2', '48');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('194', 'Telenor Sweden', '48');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('195', 'Net4Mobility', '48');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('196', 'Hutchison 3G Sweden', '48');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('197', 'Swisscom', '49');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('198', 'Sunrise UPC', '49');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('199', 'Sunrise - Historic', '49');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('200', 'Swiss Digital', '49');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('201', 'Salt Mobile', '49');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('202', 'Turk Telekom', '50');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('203', 'Turksat', '50');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('204', 'Turkcell Group', '50');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('205', 'Millenicom', '50');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('206', 'Ukrtelecom', '51');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('207', 'Datagroup', '51');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('208', 'Kyivstar', '51');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('209', 'Vega', '51');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('210', 'Velton Telecom', '51');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('211', 'Intertelecom', '51');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('212', 'International Telecommunication Company', '51');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('213', 'PEOPLEnet', '51');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('214', 'Vodafone Ukraine ', '51');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('215', 'Lifecell ', '51');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('216', 'British Telecom', '52');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('217', 'KCom', '52');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('218', 'Cable & Wireless Communications (CWC)', '52');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('219', 'Virgin Media', '52');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('220', 'COLT', '52');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('221', 'Dixons Carphone Group', '52');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('222', 'TalkTalk', '52');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('223', 'Sky', '52');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('224', 'Hutchison 3', '52');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('225', 'O2', '52');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('226', 'Vodafone', '52');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('227', 'EE', '52');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('228', 'Telenor Serbia', '42');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('229', 'Mobilna Telefonija Srbija', '42');
INSERT INTO `enercom`.`network_operators` (`id`, `name`, `country_id`) VALUES ('230', 'VIP Mobile', '42');

--insert clients
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`, `role`, `phone_number`, `email`, `created`) VALUES ('1', 'Poland', 'VECTRA', 'Michal Grzymski', ' Head of Procurement Department', '+48 502 106 660', 'm.grzymski@vectra.pl', '');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`, `role`, `email`, `created`) VALUES ('2', 'Poland', 'VECTRA', 'Iwona Gachowska ', 'Manager for  IT categories in Procurement', 'i.gachowska@vectra.pl', '');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`, `role`, `phone_number`, `email`) VALUES ('3', 'Poland', 'UPC Poland', 'Tomasz Jaroszuk', 'Transmition Manager', '+48 600 488 307', 'tomasz.jaroszuk@upc.com.pl');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`, `role`, `phone_number`, `email`) VALUES ('4', 'Poland', 'UPC Poland', 'Paweł Witek', 'Logistics Leader', '+48 600 857 054', 'Pawel.Witek@upc.pl');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`, `role`, `phone_number`, `email`) VALUES ('5', 'Poland', 'UPC Poland', 'Arkadiusz Jędrzejczak', 'Logistics Manager', '+48 600 488 757', 'Arkadiusz.Jedrzejczak@upc.pl');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`, `role`, `phone_number`, `email`) VALUES ('6', 'Poland', 'UPC Poland', 'Krzysztof Rzymski', 'Development Director', '+48 600 488 790', 'krzysztof.rzymski@upc.com.pl');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`, `role`, `phone_number`, `email`) VALUES ('7', 'Poland', 'TOYA', 'Michał Domański', 'R&D Director', '+48 797 005 062', 'm.domanski@toya.com.pl');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`, `role`, `phone_number`, `email`) VALUES ('8', 'Poland', 'Inea', 'Marcin Grochociński', 'Technology & Innovation Director', '+48 600 091 052', 'marcin.grochocinski@inea.com.pl ');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`, `role`, `phone_number`, `email`) VALUES ('9', 'Belarus', 'Mobile Service', 'Yury Levdansky', 'CEO', '+375 29 3112225', 'ly@mobiles.by');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`, `role`, `phone_number`, `email`) VALUES ('10', 'Estonia', 'Starman Group', 'Erkki Põllu', 'Head of Development', '+372 56 562169', 'erkki.pollu@starman.ee');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`, `role`, `phone_number`, `email`) VALUES ('11', 'Latvia', 'Baltcom TV', 'Dmitrijs Nikitins', 'CEO', '+ 371 22333500', 'd.nikitins@baltcom.lv');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`, `role`, `phone_number`, `email`) VALUES ('12', 'Latvia', 'Balticom', 'Ivan Sergiyenko', 'Technical Director', '+371 29484315', 'i.sergijenko@balticom.lv');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`, `role`, `phone_number`, `email`) VALUES ('13', 'Latvia', 'Livas', 'Alex Pavlov', 'CEO', '+371 26 540 208', 'alex.pavlov@livas.lv');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`, `phone_number`, `email`) VALUES ('14', 'Lituania', 'JSC \"Cgates\"', 'Marius Dabrišius', '+370 616 77751', 'Marius.Dabrisius@cgates.lt');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`, `role`, `phone_number`, `email`) VALUES ('15', 'Romania', 'RCS&RDS', 'Emil Grecu', 'CTO', '+40 770100221', 'emil.grecu@rcs-rds.ro');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`, `role`, `phone_number`, `email`) VALUES ('16', 'Romania', 'Interlan Internet eXchange S.R.L. ', 'Adrian Calineata ', 'Administrator / Executive Board Member, Interlan Association ', ' Phone +40 31 710 2428                                       mobile: +40 724.319.316 ', 'adrian.calineata@interlan.ro ');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`, `role`, `phone_number`, `email`) VALUES ('17', 'Slovakia', 'Slovanet, a.s.', 'Ing. Lucia Nošíková', 'Product manager', '+421 917390242', 'lucia.nosikova@slovanet.net');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`, `role`, `phone_number`, `email`) VALUES ('18', 'Slovakia', 'Slovanet, a.s.', 'Ing. Sandra Plišková', 'Product manager', '+421 904 284 771', 'sandra.pliskova@slovanet.net');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`, `role`, `phone_number`, `email`) VALUES ('19', 'Slovakia', 'Satro', 'Martin Kopča', 'Executive Director', '+421 905 259 184', 'martin.kopca@satro.sk ');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`, `role`, `phone_number`, `email`) VALUES ('20', 'Slovakia', 'T2', 'Janez Štravs', 'Head of IPTV and Service Development Sector', '+386 (0) 64 13 09 33', 'janez.stravs@t-2.com');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`) VALUES ('21', 'Albania', 'Vodafone', 'Ervin Begu ');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`) VALUES ('22', 'Albania', 'Vodafone', 'Aida Mone ');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`) VALUES ('23', 'Romania', 'Vodafone', 'Achilleas Kanaris');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`) VALUES ('24', 'Greece', 'Vodafone', 'Nik Vilcenau');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`) VALUES ('25', 'Albania', '4iG', 'Ilir Duka');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`) VALUES ('26', 'Kosovo', 'IPKO', 'Arben Sylejmani');
INSERT INTO `enercom`.`clients` (`id`, `country`, `company`, `contact`) VALUES ('27', 'Kosovo', 'Kujtesa', 'Shpend Bakalli');


--insert products
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('1', 'LTT7', 'Tool, Term Locking  ', '20', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('2', 'PCT11A', 'Series 11, 5/8\" Feed-Thru Connector, Universal ', '0', '17500', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('3', 'PCT59FT', 'Port Terminator  ', '10000', '15000', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('4', 'PCT625FCHG', 'F Female to KS Adapter, -30 RL  ', '0', '2000', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('5', 'PCT6IUF', 'Connector,Series6,60%thruQuadIECF ', '32468', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('6', 'PCT71F', 'F Male to F Male Adapter  ', '2000', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('7', 'PCT81FSP', 'Adapter, F-Male  ', '0', '60000', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('8', 'PCTAIOCT', 'All-in-One Compression tool for all PCT Compression Connectors', '10', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('9', 'PCTBNC59', 'BNC COMPRESSION CONNECTOR RG59  ', '7500', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('10', 'PCTBNC6', 'UNIVERSAL, BNC COMPRESSION  ', '0', '6000', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('11', 'PCTBNC9', 'Series 9 Headend Compression Connector, BNC ', '10995', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('12', 'PCTDRS11RA', 'Series 11 Universal Compression Connector, Right Angle ', '1900', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('13', 'PCTDRS59', 'Connector, PCT-DRS-59  ', '150', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('14', 'PCTDRS59IFNT', 'CONNECTOR F RG59 COMP IEC FEMALE NT ', '2400', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('15', 'PCTDRS6', 'Connector, PCT-DRS-6  ', '700', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('16', 'PCTDRS6IFNT', 'DRS Comp Conn 6 IEC Female Bi-Tri ', '50', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('17', 'PCTDRS6IMNT', 'DRS Comp Conn, 6 IEC, Male, Bi-Tri ', '0', '40000', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('18', 'PCTDRS6LNT', 'CONNECTOR,F RG6 COMP SELF LOCKING ', '200', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('19', 'PCTDRS7', 'Series 7 Universal CompressionConnector ', '3000', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('20', 'PCTF81G', 'Adapter, F-Male, Dual Flat, 30.9mm ', '17500', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('21', 'PCTFRS6LMG', 'Series 6 Universal Compression Connector, Torque Retaining, Continuous Ground, 21mm', '524859', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('22', 'PCTIFFF', 'IEC Female to F-Female Adapter  ', '7000', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('23', 'PCTIFFM', 'Adapter,IECFmaleFMale  ', '11990', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('24', 'PCTIMFF', 'Adapter,IECMaleFFmale  ', '8619', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('25', 'PCTIMFM', 'Adapter,IECMaleFMale  ', '6047', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('26', 'PCTQP11LNT', 'RG11 Postless Compression Connector w/Qu ', '0', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('27', 'PCTQP59LNT', 'RG59 Postless Compression Connector w/Qu ', '0', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('28', 'PCTQP6LNT', 'RG6 Postless Compression Connector w/Qui ', '0', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('29', 'PCTRCA59', 'Series 59 Universal Compressiories 6 & 59 - 18mm, Series 11 ', '8768', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('30', 'PCTRCA6', 'Connector RCA RG6 Universal Compression ', '4009', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('31', 'PCTTPGR', 'Locking Terminator, 75 Ohm Resistor ', '36000', '30000', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('32', 'PCTTPGRW', '75 ohm locking terminator with weather ', '5990', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('33', 'PCTTRS11LMG', 'Series 11 Universal Compression Connector, Torque Retaining, Continuos Ground', '34450', '33000', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('34', 'PCTTRS11LRA', 'Series 11 Universal Compression Connector, Torque Retaining, Right Angle', '1250', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('35', 'PCTTRS59LMG', 'Series 59 Universal Compression Connector, Torque Retaining , Continous Ground, 18mm', '0', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('36', 'PCTTRS6IFNT', 'TRS Comp Conn 6 IEC-F Bi-Quad NT ', '1500', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('37', 'PCTTRS6LMG', 'Series 6 Universal Compression Connector, Torque Retaining, Continous Ground, 18mm', '256493', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('38', 'PCTTRS6LNT', 'Series 6 Universal Compression Connector, Torque Retaining, Ni Tin, 18mm', '113100', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('39', 'PCTTRS6LSR', 'TRS Comp Conn 6 Locking Bi-Quad w/ SR ', '1450', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('40', 'PCTTRS9IFNT', 'Series 9 Universal IEC Compresion Connector, Female, 18mm ', '3500', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('41', 'PCTTRS9LNT', 'Series 9 Universal Compression Connector, Torque Retaining, Ni Tin, 18mm', '0', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('42', 'PCTTRS9NT', 'TRS Comp Conn, 9 Bi-Quad NT  ', '450', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('43', 'PCTTRSHE59L', 'TRS Comp Conn 59 HE Locking Bi-Quad ', '0', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('44', 'PCT10002W', 'Drop Splitter, 2 Way, Horizontal, 1GHz ', '0', '15000', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('45', 'PCT10003V', 'Splitter,Drop,Gold,Series,3Way  ', '4798', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('46', 'PCT10003VRH', 'Splitter3Way1GHzVert  ', '8400', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('47', 'PCT10003W', 'Drop Splitter, 3 Way, Horizontal, 1GHz ', '0', '3000', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('48', 'PCT10003WB', 'Splitter 3-way digital balanced  ', '13900', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('49', 'PCT10004V', 'Splitter,Drop,Gold,Series,4Way  ', '5850', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('50', 'PCT10004W', 'Splitter,4 Way 1GHz  ', '3200', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('51', 'PCT10006V', 'Drop Splitter, 6 Way, Vertical1GHz ', '500', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('52', 'PCT10006W', 'Splitter indoor 6-way Gold Horizontal ', '1420', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('53', 'PCT10008V', 'Splitter indoor ', '7700', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('54', 'PCT10008W', 'Splitter,8 Way 1GHz  ', '2462', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('55', 'PCTD32', 'Drop Splitter, 2-Way, 1.2 GHz  ', '2116', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('56', 'PCTD33B', 'Drop Splitter, 3-Way, 1.2 GHz,Balanced ', '5447', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('57', 'PCTD34', 'Drop Splitter, 4-Way, 1.2 GHz  ', '3400', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('58', 'PCTD38', 'Drop Splitter, 8-Way, 1.2 GHz  ', '2020', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('59', 'PCTIT1W06', 'INDOOR GOLD SERIES 1 GHz 1-WAY TAP 06dB ', '1200', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('60', 'PCTIT1W10', 'INDOOR GOLD SERIES 1 GHz 1-WAY  ', '1090', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('61', 'PCTIT1W12', 'Drop Tap, 1-Way, 12 dB  ', '1919', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('62', 'PCTIT1W16', 'Drop Tap, 1-Way, 16 dB  ', '12660', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('63', 'PCTIT1W20', 'Drop Tap, 1-Way, 20 dB  ', '7349', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('64', 'PCTIT1W24', 'Tap,1Way1GHz24dBGold  ', '200', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('65', 'PCTIT2W08', 'Drop Tap, 2-Way, 08 dB  ', '1375', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('66', 'PCTIT2W10', 'Drop Tap, 2-Way, 10 dB  ', '1000', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('67', 'PCTIT2W12', 'Drop Tap, 2-Way, 12 dB  ', '4083', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('68', 'PCTIT2W16', 'Drop Tap, 2-Way, 16 dB  ', '1300', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('69', 'PCTIT2W20', 'INDOOR GOLD SERIES 1 GHz 2-WAY TAP 20dB ', '715', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('70', 'PCTIT2W24', 'Tap, 2 Way 1GHZ 24dB  ', '1296', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('71', 'PCTIT3W10', 'INDOOR GOLD SERIES 1 GHz 3-WAY TAP 10B ', '498', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('72', 'PCTIT3W12', 'Drop Tap, 3-Way, 12 dB  ', '1285', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('73', 'PCTIT3W16', 'INDOOR GOLD SERIES 1 GHz 3-WAY TAP 16 ', '1201', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('74', 'PCTIT3W20', 'Tap,3way1GHz16dBGold  ', '760', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('75', 'PCTIT4W08', 'Drop Tap, 4-Way, 08 dB  ', '550', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('76', 'PCTIT4W10', 'Drop Tap, 4-Way, 10 dB  ', '340', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('77', 'PCTIT4W11', 'INDOOR GOLD SERIES 1 GHz 4-WAY TAP 11dB ', '0', '620', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('78', 'PCTIT4W12', 'Drop Tap, 4-Way, 12 dB  ', '410', '820', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('79', 'PCTIT4W14', 'Tap, 4 Way 1GHz 14dB Gold  ', '0', '800', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('80', 'PCTIT4W17', 'INDOOR GOLD SERIES 1 GHz 4-WAY TAP 17dB ', '0', '700', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('81', 'PCTIT4W20', 'Drop Tap, 4-Way, 20 dB  ', '0', '620', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('82', 'PCTIT4W23', 'INDOOR GOLD SERIES 1 GHz 4-WAY TAP 23dB ', '0', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('83', 'PCTIT4W26', 'INDOOR GOLD SERIES 1 GHz 4-WAY TAP 26dB ', '0', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('84', 'PCTIT8W12', 'Tap,8Way1GHz12dBGold  ', '74', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('85', 'PCTIT8W14', 'Tap, 8 Way 1GHz 14dB Gold  ', '0', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('86', 'PCTIT8W17', 'Tap, 8 Way 1GHz 20dB Gold  ', '0', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('87', 'PCTIT8W20', 'Tap, 8 Way 1GHz 20dB Gold  ', '0', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('88', 'PCTIT8W23', 'Tap, 8 Way 1GHz 23dB Gold  ', '0', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('89', 'PCTIT8W26', 'Tap, 8 Way 1GHz 26dB Gold  ', '0', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('90', 'PCTMIT1W20', 'Tap,Mini1Way20dBGold  ', '1000', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('91', 'PCTNGN3T', 'Splitter, 3 Way 1GHz T&G  ', '76', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('92', 'PCTNGNII3SB', 'Drop Splitter Genesys II 3 Way Bal ', '28', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('93', 'PCTNGNII3T', 'Splitter, 3 Way Dig 1GHz T&G  ', '399', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('94', 'PCTNGNII4S', 'Drop Splitter Genesys II 4 Way  ', '2545', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('95', 'PCTNGNII4SV', 'Drop Splitter Genesys II 4 Way Vert ', '2600', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('96', 'PCTNGNII8S', 'Drop Splitter Genesys II 8 Way  ', '2757', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('97', 'PCTNGNII8SV', 'Drop Splitter Genesys II 8 Way Vert ', '7105', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('98', 'PCTNGNIIIT1S12', 'Tap Drop Genesys II 1 Way 12dB  ', '200', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('99', 'PCTNGNIIIT1S20', 'Tap Drop Genesys II 1 Way 20dB  ', '2400', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('100', 'PCTFAM03', 'pad attenuator, 03dB  ', '4987', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('101', 'PCTFAM06', 'pad attenuator, 06dB  ', '478', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('102', 'PCTFAM10', 'pad attenuator, 10dB  ', '1000', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('103', 'PCTFAM12', 'pad attenuator,  12dB  ', '1500', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('104', 'PCTFAM16', 'Pad Attenuator, 16 dB  ', '1000', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('105', 'PCTFAM20', 'Pad Attenuator 20dB  ', '1000', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('106', 'PCTFNAM06', 'Pad Attenuator with Fixed Nut 6 dB ', '500', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('107', 'PCTFNAM08', 'Pad Attenuator with Fixed Nut 8dB ', '41', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('108', 'PCTFNAM10', 'Pad Attenuator with Fixed Nut 10 dB ', '1500', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('109', 'PCTFNAM12', 'Pad Attenuator with Fixed Nut 12dB ', '329', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('110', 'PCTFNAM16', 'Pad Attenuator with Fixed Nut 16dB ', '490', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('111', 'PCTFNAM20', 'Pad Attenuator with Fixed Nut 20dB ', '314', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('112', 'PCTHDC1512B', 'Outdoor Coupler, 12dB, 1GHz  ', '155', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('113', 'PCTHDC158B', 'Outdoor Coupler, 8dB, 1GHzOutdoor DC Trad Series 8dB 15A ', '78', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('114', 'PCTHDCA1512B', 'Outdoor Coupler, 12dB, 1.2GHz  ', '180', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('115', 'PCTHDCA158B', 'Outdoor Coupler, 8dB, 1.2GHz  ', '40', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('116', 'PCTHPF50A', 'High Pass Filter, 50MHz  ', '1990', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('117', 'PCTHPF80A', 'High Pass Filter, 80MHz  ', '2865', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('118', 'PCTHSP215B', 'Outdoor Splitter, 2-Way  ', '0', '200', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('119', 'PCTHSP315B', 'Outdoor Splitter, 3-Way, Balanced ', '0', '200', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('120', 'PCTHSP3U15B', 'Outdoor Splitter, 3-Way, Unbalanced ', '0', '200', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('121', 'PCTHSPA215B', 'Outdoor Splitter, 2-Way, 1.2GHz ', '357', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('122', 'PCTHSPA315B', 'Outdoor Splitter, 3-Way, Balanced, 1.2GHz ', '388', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('123', 'PCTHSPA3U15B', 'Outdoor Splitter, 3-Way, Unbalanced, 1.2GHz ', '0', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('124', 'PCTLPIA20A', 'Outdoor Power Inserter, 20A, 1218MHz ', '203', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('125', 'PCTOSP3HB', 'Splitter,Line3WayBusBar  ', '145', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('126', 'PCTRTP211', 'Outdoor Tap 2 Way RTP Series 11dB ', '31', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('127', 'PCTRTP214', 'Outdoor Tap 2 Way RTP Series 14dB ', '39', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('128', 'PCTRTP217', 'Outdoor Tap 2 Way RTP Series 17dB ', '31', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('129', 'PCTRTP220', 'Outdoor Tap 2 Way RTP Series 20dB ', '34', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('130', 'PCTRTP223', 'Outdoor Tap 2 Way RTP Series 23dB ', '35', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('131', 'PCTRTP24T', 'Outdoor Tap 2 Way RTP Series 4dB ', '38', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('132', 'PCTRTPCS15', 'Cable Simulator for RTP Series Taps 15dB ', '4386', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('133', 'PCTTP21204T', 'Outdoor Tap 2 Way Trad Series 4dB ', '555', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('134', 'PCTTP21208', 'Outdoor Tap, 2-Way, 08dB  ', '123', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('135', 'PCTTP21211', 'Outdoor Tap, 2-Way, 11dB  ', '100', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('136', 'PCTTP21214', 'Outdoor Tap, 2-Way, 14dB  ', '130', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('137', 'PCTTP21217', 'Outdoor Tap, 2-Way, 17dB17dB ', '290', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('138', 'PCTTP21220', 'Outdoor Tap, 2-Way, 20dB  ', '320', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('139', 'PCTTP21223', 'Outdoor Tap, 2-Way, 23dB  ', '200', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('140', 'PCTTP21226', 'Outdoor Tap 2 Way Trad Series 26dB ', '12', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('141', 'PCTTP41208T', 'Outdoor Tap, 4-Way, 08dB8dB ', '0', '400', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('142', 'PCTTP41211', 'Outdoor Tap, 4-Way, 11dB  ', '0', '380', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('143', 'PCTTP41214', 'Outdoor Tap, 4-Way, 14dB  ', '0', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('144', 'PCTTP41217', 'Outdoor Tap, 4-Way, 17dB  ', '0', '1420', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('145', 'PCTTP41220', 'Outdoor Tap, 4-Way, 20dB  ', '0', '1418', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('146', 'PCTTP41223', 'Outdoor Tap, 4-Way, 23dB23dB ', '0', '1400', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('147', 'PCTTP41226', 'Outdoor Tap 4 Way Trad Series 26dB ', '0', '1335', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('148', 'PCTTP81211T', 'Outdoor Tap, 8-Way, 11dB  ', '0', '225', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('149', 'PCTTP81214', 'Outdoor Tap, 8-Way, 14dB  ', '0', '270', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('150', 'PCTTP81217', 'Outdoor Tap, 8-Way, 17dB17dB ', '0', '125', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('151', 'PCTTP81220', 'Outdoor Tap, 8-Way, 20dB  ', '0', '105', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('152', 'PCTTP81223', 'Outdoor Tap, 8-Way, 23dB  ', '0', '254', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('153', 'PCTTP81226', 'Outdoor Tap 8 Way Trad Series26dB ', '0', '259', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('154', 'PCTTPA21211', 'Outdoor Tap, 2-Way, 11dB, 1218MHz ', '13', '232', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('155', 'PCTTPA21217', 'Outdoor Tap, 2-Way, 17dB, 1218MHz ', '16', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('156', 'PCTTPA21223', 'Outdoor Tap, 2-Way, 23dB, 1218MHz ', '32', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('157', 'PCTTPA41211', 'Outdoor Tap, 4-Way, 11dB, 1218MHz ', '0', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('158', 'PCTTPA41214', 'Outdoor Multimedia Tap 4 Way,1218MHz T ', '0', '400', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('159', 'PCTTPA41217', 'Outdoor Tap, 4-Way, 17dB, 1218MHz  ', '0', '400', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('160', 'PCTTPA41220', 'Outdoor Tap, 4-Way, 20dB, 1218MHz ', '0', '400', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('161', 'PCTTPA41223', 'Outdoor Tap, 4-Way, 23dB, 1218MHz  ', '556', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('162', 'PCTTPA41226', 'Outdoor Tap, 4-Way, 26dB, 1218MHz ', '372', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('163', 'PCTTPC211', 'Outdoor Tap, 2-Way, 11dB, 1.2GHz, w Plug-Ins ', '49', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('164', 'PCTTPC214', 'Outdoor Tap, 2-Way, 14dB, 1.2GHz, w Plug-Ins ', '43', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('165', 'PCTTPC217', '2 way 1.2 GHz outdoor tap 17 d  ', '99', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('166', 'PCTTPC220', '2 way 1.2 GHz outdoor tap 20 d  ', '99', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('167', 'PCTTPC223', '2 way 1.2 GHz outdoor tap 23 d  ', '99', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('168', 'PCTTPC28', '2 way 1.2 GHz outdoor tap 8 dB  ', '99', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('169', 'PCTTPC2N11', 'Outdoor Tap, 1250 MHz, 2-way, 11 dB, Plug-insSA Housing, Narrow', '50', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('170', 'PCTTPC2N14', 'Outdoor Tap, 1250 MHz, 2-way, 14 dB, Plug-insSA Housing, Narrow', '50', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('171', 'PCTTPC2N17', 'Outdoor Tap, 1250 MHz, 2-way, 17 dB, Plug-insSA Housing, Narrow', '50', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('172', 'PCTTPC2N20', 'Outdoor Tap, 1250 MHz, 2-way, 20 dB, Plug-insSA Housing, Narrow', '50', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('173', 'PCTTPC2N23', 'Outdoor Tap, 1250 MHz, 2-way, 23 dB, Plug-insSA Housing, Narrow', '50', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('174', 'PCTTPC2N26', 'Outdoor Tap, 1250 MHz, 2-way, 26 dB, Plug-insSA Housing, Narrow', '28', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('175', 'PCTTPC2N29', 'Outdoor Tap, 1250 MHz, 2-way,  29 dB, Plug-insSA Housing, Narrow', '50', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('176', 'PCTTPC2N32', 'Outdoor Tap, 1250 MHz, 2-way, 32 dB, Plug-insSA Housing, Narrow', '50', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('177', 'PCTTPC2N35', 'Outdoor Tap, 1250 MHz, 2-way, 35 dB, Plug-insSA Housing, Narrow', '50', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('178', 'PCTTPC2N4T', 'Outdoor Tap, 1250 MHz, 2-way, 4 dB Terminated, Plug-insSA Housing, Narrow', '50', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('179', 'PCTTPC2N8', 'Outdoor Tap, 1250 MHz, 2-way, 8 dB, Plug-insSA Housing, Narrow', '50', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('180', 'PCTTPC423', '4 way 1.2 GHz outdoor tap 23 d  ', '58', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('181', 'PCTTPC4N11', 'Outdoor Tap, 4-Way, 11dB, 1.2 GHz, w Plug-Ins, Narrow Housin ', '30', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('182', 'PCTTPC4N23', 'Outdoor Tap, 4-Way, 23dB, 1.2GHz, w Plug-Ins, Narrow Housin ', '15', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('183', 'PCTTPC4N26', 'Outdoor Tap, 4-Way, 26dB, 1., Outdoor Tap, 4-Way, 26dB, 1.2  ', '22', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('184', 'PCTTPC4N32', 'Outdoor Tap, 1250 MHz, 4-way,332 dB, Plug-insSA Housing, Narrow', '50', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('185', 'PCTTPC4N35', 'Outdoor Tap, 1250 MHz, 4-way,335 dB, Plug-insSA Housing, Narrow', '50', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('186', 'PCTTPC823', 'Outdoor Tap, 8-Way, 23dB, 1.2 GHz, w Plug-Ins ', '20', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('187', 'PCTTPC826', 'Outdoor Tap, 8-Way, 26dB, 1.2GHz, w Plug-Ins ', '2', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('188', 'A1177TSVM1P', 'RG11 1Prep Tri 77% PVC .072Msgr, 305M ', '156', '2100', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('189', 'A677TSV1PW', 'Series 6, 1Prep, Tri Shield 77% Coaxial Cable, White, 305M ', '0', '5616', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `quantity_on_production`, `status`) VALUES ('190', 'A677TSVM1P', 'RG6 1Prep Tri 77% .051\" Msgr305m ', '0', '120', '1');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('191', 'HFC500F', '500 Series 75 Ohm Trunk and Distributio ', '732', '0');
INSERT INTO `enercom`.`products` (`id`, `name`, `description`, `quantity_on_stock`, `status`) VALUES ('192', 'HFC540M', '540 HFC cable, aerial, messeng  ', '1410', '0');
